config/routes.rb
Rails.application.routes.draw do

  # resources :employees
  devise_for :companies
  root to: "departments#index"

  resources :departments do
    resources :employees
  end 
     # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :departments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :company
  has_many :employees, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department

  def self.search(search)
    if search
      where('first_name LIKE ?', "%#{search}%")
    else
      search = []
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :rif])
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
    @department = Department.new
    @employees = Employee.all
    if params[:search]
      @search = Employee.all.where('first_name LIKE ?', "%#{params[:search]}%")
    else
      params[:search] = []
    end
    # @value = nil
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
    @departments = Department.all
    @employees = Employee.all
    if params[:search]
      @search = Employee.all.where('first_name LIKE ?', "%#{params[:search]}%")
    else
      params[:search] = []
    end
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params.merge!({company_id:current_company.id}))

    respond_to do |format|
      if @department.save
        format.html { redirect_to root_path, notice: 'El departamento fue creado exitosamente.' }
        format.json { render :index, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to root_path, notice: 'El departamento fue editado exitosamente.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'El departamento fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!

  # GET /employees
  # GET /employees.json
  def index
    # @search = Employee.search(params[:search])
    @employees = Employee.where(department_id: params[:department_id])
    @employee = Employee.new
    @department = Department.find(params[:department_id])
    if params[:search]
      @search = Employee.all.where('first_name LIKE ?', "%#{params[:search]}%")
    else
      params[:search] = []
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @department = Department.find(params[:department_id])
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @department = Department.find(params[:department_id])
  end

  # GET /employees/1/edit
  def edit
    @employees = Employee.where(department_id: params[:department_id])
    @department = Department.find(params[:department_id])
    # @search = Employee.search(params[:search])
    if params[:search]
      @search = Employee.all.where('first_name LIKE ?', "%#{params[:search]}%")
    else
      params[:search] = []
    end
  end

  # POST /employees
  # POST /employees.json
  def create
    # @employee = Employee.new(employee_params)
    @department = Department.find(params[:department_id])
    @employee = Employee.new(employee_params.merge!({:department=>@department}))

    respond_to do |format|
      if @employee.save
        format.html { redirect_to department_employees_path, notice: 'El empleado fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    @department = Department.find(params[:department_id])
    respond_to do |format|
      if @employee.update(employee_params.merge!({:department=>@department}))
        format.html { redirect_to department_employees_path, notice: 'El empleado fue editado exitosamente.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to department_employees_path, notice: 'El empleado fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :dni, :cellphone, :email, :bank, :account_type, :account_number, :phone, :emergency_phone, :department_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_form.html.haml
.container
  .row
    .col-12.card.pb-3
      = form_for @department do |f|
        - if @department.errors.any?
          #error_explanation
            %h2= "#{pluralize(@department.errors.count, "error")} prohibited this department from being saved:"
            %ul
              - @department.errors.full_messages.each do |message|
                %li= message

        .field.mt-2
          = f.label :nombre_del_departamento
          = f.text_field :name, :required => true,class: "input-group"
        .actions.mt-2
          = f.submit 'Guardar', class: "btn btn-primary input-group"

app/views/departments/_search.html.haml
.col-10
    = form_tag root_path, method: :get do
        .row
            .col-10
                = text_field_tag :search, params[:search], :placeholder => "Buscar empleado", :class => "input-group"
            .col-2
                = submit_tag 'Search', :name => nil, :class => "btn btn-primary"
.col-2.text-right
    = link_to "Cerrar sesión", destroy_company_session_path, method: :delete, class: "btn btn-danger"

app/views/departments/edit.html.haml
.container.mt-4
    .row.grey
        = render 'search'
    -if(params[:search].empty?)
        .row
            .col-12.notifications.text-center
                %p#notice= notice
        .row.justify-content-center
            .col-7
                %h3 Departamentos
            
                - if @departments.empty?
                    %img.card.emptydep(src="https://www.cdc.gov/ncbddd/adhd/images/adhd-behavior-therapy-600x300.png")/
                - else
                    %table.table.border
                        %thead
                            %tr
                                %th Nombre del departamento
                                %th.text-center Cantidad de empleados
                                %th.text-center Acciones
        
                        %tbody
                            - @departments.each do |department|
                                %tr
                                    %td= link_to department.name, department_employees_path(department)
                                    %td.text-center= @employees.where(:department_id => department.id).length
                                    %td.text-center
                                        = link_to image_tag('grupo(1).png'), department_employees_path(department)
                                        = link_to image_tag('lapiz.png'), edit_department_path(department)
                                        = link_to image_tag('basura.png'), department, method: :delete, data: { confirm: 'También se eliminarán los empleados que pertenezcan a este departamento. ¿Está segúro?' }
        
                    %br
            .col-3
                %h4 Editar departamento
    
                = render 'form'
    -elsif(@search.lenght != 0)
        .row.justify-content-center.mt-5
            .col-7
                %h3
                    = link_to image_tag('flecha-atras(2).png'), root_path
                    Resultado de la búsqueda  
                %table.table.border
                    %thead
                        %tr
                            %th Cédula
                            %th Nombre
                            %th Celular
                            %th.text-center Departamento
                            %th.text-center Acciones
                    %tbody
                        - @search.each do |employee|
                            %tr
                                %td= employee.dni
                                %td= employee.first_name
                                %td= employee.cellphone
                                %td.text-center
                                    = employee.department_id
                                %td.text-center
                        -# = link_to image_tag('lapiz.png'), edit_department_employee_path(@department, employee)
                        -# = link_to image_tag('basura.png'), [@department, employee], method: :delete, data: { confirm: '¿Está segúro de borrar este empleado?' }
    - else
        .row.justify-content-center.mt-5
            .col-4
                %h4
                    = link_to image_tag('flecha-atras(2).png'), root_path
                    Resultado de la búsqueda  
                .image2.card.text-center
                    %h6.mt-2 Ningun empleado coincide con la búsqueda
        
                
      

app/views/departments/index.html.haml
.container.mt-4
  .row.grey
    = render 'search'
  -if(params[:search].empty?)
    .row.justify-content-center
      .col-5.notifications.text-center
        -if(notice != nil)
          .alert.alert-success.alert-dismissible
            %a.close(href="#" data-dismiss="alert" aria-label="close") &times
            %p#notice= notice
    .row.justify-content-center
      .col-7
        %h3 Departamentos
        
        - if @departments.empty?
          .image.card.text-center
            %h4.mt-2 Aún no hay departamentos
            %span.small.textimage Agrega un departamento en la sección Nuevo departamento
        - else
          %table.table.border
            %thead
              %tr
                %th Nombre del departamento
                %th.text-center Cantidad de empleados
                %th.text-center Acciones

            %tbody
              - @departments.each do |department|
                %tr
                  %td= link_to department.name, department_employees_path(department)
                  %td.text-center= @employees.where(:department_id => department.id).length
                  %td.text-center
                    = link_to image_tag('grupo(1).png'), department_employees_path(department)
                    = link_to image_tag('lapiz.png'), edit_department_path(department)
                    = link_to image_tag('basura.png'), department, method: :delete, data: { confirm: 'También se eliminarán los empleados que pertenezcan a este departamento. ¿Está segúro?' }

          %br
      .col-3
        %h4 Nuevo departamento

        = render 'form'
  -elsif(@search.length != 0)
    .row.justify-content-center.mt-5
      .col-7
        %h3
          = link_to image_tag('flecha-atras(2).png'), root_path
          Resultado de la búsqueda  
        %table.table.border
          %thead
            %tr
              %th Cédula
              %th Nombre
              %th Celular
              %th.text-center Departamento
              %th.text-center Acciones
          %tbody
            - @search.each do |employee|
              %tr
                %td= employee.dni
                %td= employee.first_name
                %td= employee.cellphone
                %td.text-center
                  = employee.department_id
                %td.text-center
                  -# = link_to image_tag('lapiz.png'), edit_department_employee_path(@department, employee)
                  -# = link_to image_tag('basura.png'), [@department, employee], method: :delete, data: { confirm: '¿Está segúro de borrar este empleado?' }
  -else
    .row.justify-content-center.mt-5
      .col-4
        %h4
          = link_to image_tag('flecha-atras(2).png'), root_path
          Resultado de la búsqueda  
        .image2.card.text-center
          %h6.mt-2 Ningun empleado coincide con la búsqueda
                           

app/views/departments/new.html.haml
%h1 New department

= render 'form'

= link_to 'Back', departments_path

app/views/departments/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @department.name
%p
  %b Company:
  = @department.company

= link_to 'Edit', edit_department_path(@department)
\|
= link_to 'Back', departments_path

app/views/employees/_form.html.haml
.row.card.pb-3.pt-2
  .col-12
    = form_for([@department, @employee]) do |f|
      - if @employee.errors.any?
        #error_explanation
          %h2= "#{pluralize(@employee.errors.count, "error")} prohibited this employee from being saved:"
          %ul
            - @employee.errors.full_messages.each do |message|
              %li= message
      .row
        .col-6.mt-1
          .field
            = f.label :primer_nombre
            = f.text_field :first_name, :required => true, class: "input-group"
        .col-6.mt-1
          .field
            = f.label :apellido
            = f.text_field :last_name, :required => true, class: "input-group"
        .col-6.mt-1
          .field
            = f.label :cédula
            = f.text_field :dni, :required => true, class: "input-group"
        .col-6.mt-1
          .field
            = f.label :celular
            = f.text_field :cellphone, :required => true, class: "input-group"
        .col-12.mt-1
          .field
            = f.label :correo_electrónico
            = f.text_field :email, class: "input-group"
        .col-6.mt-1
          .field
            = f.label :banco
            = f.text_field :bank, class: "input-group"
        .col-6.mt-1
          .field
            = f.label :tipo_de_cuenta
            = f.text_field :account_type, class: "input-group"
        .col-12.mt-1
          .field
            = f.label :nro_de_cuenta
            = f.text_field :account_number, class: "input-group"
        .col-6.mt-1
          .field
            = f.label :teléfono_fijo
            = f.text_field :phone, class: "input-group"
        .col-6.mt-1
          .field
            = f.label :teléfono_emergencia
            = f.text_field :emergency_phone, class: "input-group"
        .col-12.mt-2
          .actions
            = f.submit 'Guardar', class: "btn btn-primary input-group"

app/views/employees/_search.html.haml
.col-10
    = form_tag department_employees_path, method: :get do
        .row
            .col-10
                = text_field_tag :search, params[:search], :placeholder => "Buscar empleado", :class => "input-group"
            .col-2
                = submit_tag 'Search',:name => nil, :class => "btn btn-primary"
.col-2.text-right
    = link_to "Cerrar sesión", destroy_company_session_path, method: :delete, class: "btn btn-danger"

app/views/employees/edit.html.haml
.container.mt-4
    .row.grey
        = render 'search'
    -if(params[:search].empty?)
        .row
            .col-12.notifications
        .row.justify-content-center
            .col-7
                .row
                    .col-1
                        = link_to image_tag('flecha-atras(2).png'), root_path
                    .col
                        %h3 
                            Empleados de
                            = @department.name 
                -if @employees.empty?
                    %img.card.emptydep(src="https://www.cdc.gov/ncbddd/adhd/images/adhd-behavior-therapy-600x300.png")/
                -else
                    %table.table.border
                        %thead
                            %tr
                                %th Cédula
                                %th Nombre
                                %th Celular
                                %th.text-center Acciones

                        %tbody
                            - @employees.each do |employee|
                                %tr
                                    %td= employee.dni
                                    %td
                                        = employee.first_name
                                        = employee.last_name
                                    %td
                                        = employee.cellphone
                                        -# %td= link_to 'Show', department_employee_path(@department, employee)
                                    %td.text-center
                                        = link_to image_tag('lapiz.png'), edit_department_employee_path(@department, employee)
                                        -# %td= link_to 'Edit', department_employees_path(@department, @employee)
                                        = link_to image_tag('basura.png'), [@department, employee], method: :delete, data: { confirm: '¿Está segúro de borrar este empleado?' }

                    %br
            .col-4
                %h3 Editar Empleado

                = render 'form'
    - else
        .row.justify-content-center.mt-5
            .col-7
            %h3
                = link_to image_tag('flecha-atras(2).png'), department_employees_path 
                Resultado de la búsqueda  
            %table.table.border
                %thead
                %tr
                    %th Cédula
                    %th Nombre
                    %th Celular
                    %th.text-center Departamento
                    %th.text-center Acciones
                %tbody
                - @search.each do |employee|
                    %tr
                    %td= employee.dni
                    %td= employee.first_name
                    %td= employee.cellphone
                    %td.text-center
                        = @department.name
                    %td.text-center
                        = link_to image_tag('lapiz.png'), edit_department_employee_path(@department, employee)
                        = link_to image_tag('basura.png'), [@department, employee], method: :delete, data: { confirm: '¿Está segúro de borrar este empleado?' }
    
      

app/views/employees/index.html.haml
.container.mt-4
  .row.grey
    = render 'search'
  -if(params[:search].empty?)  
    .row.justify-content-center
      .col-5.notifications.text-center
        -if(notice != nil)
          .alert.alert-success.alert.dismissible
            %a.close(href="#" data-dismiss="alert" aria-label="close") &times
            %p#notice= notice
    .row.justify-content-center
      .col-7
        .row
          .col-1
            = link_to image_tag('flecha-atras(2).png'), root_path
          .col
            %h3 
              Empleados de 
              = @department.name
        -if @employees.empty?
          .image.text-center.card
            %h4.mt-2 Aún no hay empleados
            %span.small.textimage Agrega un empleado en la sección Nuevo empleado
        -else
          %table.table.border
            %thead
              %tr
                %th Cédula
                %th Nombre
                %th Celular
                %th.text-center Acciones 

            %tbody
              - @employees.each do |employee|
                %tr
                  %td= employee.dni
                  %td
                    = employee.first_name
                    = employee.last_name
                  %td
                    = employee.cellphone
                  %td.text-center
                    = link_to image_tag('lapiz.png'), edit_department_employee_path(@department, employee)
                    = link_to image_tag('basura.png'), [@department, employee], method: :delete, data: { confirm: '¿Está segúro de borrar este empleado?' }

          %br
      .col-4
        %h3 Nuevo empleado
        = render 'form'
  -elsif(@search.length != 0)
    .row.justify-content-center.mt-5
      .col-7
        %h3
          = link_to image_tag('flecha-atras(2).png'), department_employees_path 
          Resultado de la búsqueda  
        %table.table.border
          %thead
            %tr
              %th Cédula
              %th Nombre
              %th Celular
              %th.text-center Departamento
              %th.text-center Acciones
          %tbody
            - @search.each do |employee|
              %tr
                %td= employee.dni
                %td= employee.first_name
                %td= employee.cellphone
                %td.text-center
                  = @department.name
                %td.text-center
                  = link_to image_tag('lapiz.png'), edit_department_employee_path(@department, employee)
                  = link_to image_tag('basura.png'), [@department, employee], method: :delete, data: { confirm: '¿Está segúro de borrar este empleado?' }
  - else
    .row.justify-content-center.mt-5
      .col-4
        %h4
          = link_to image_tag('flecha-atras(2).png'), department_employees_path
          Resultado de la búsqueda  
        .image2.card.text-center
          %h6.mt-2 Ningun empleado coincide con la búsqueda
    

app/views/employees/new.html.haml
%h1 New employee

= render 'form'

= link_to 'Back', department_employees_path(@department)

app/views/employees/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @employee.first_name
%p
  %b Last name:
  = @employee.last_name
%p
  %b Dni:
  = @employee.dni
%p
  %b Cellphone:
  = @employee.cellphone
%p
  %b Email:
  = @employee.email
%p
  %b Bank:
  = @employee.bank
%p
  %b Account type:
  = @employee.account_type
%p
  %b Account number:
  = @employee.account_number
%p
  %b Phone:
  = @employee.phone
%p
  %b Emergency phone:
  = @employee.emergency_phone
%p
  %b Department:
  = @employee.department

= link_to 'Edit', edit_department_employee_path(@department, @employee)
\|
= link_to 'Back', department_employees_path

app/views/layouts/_search.html.haml
%h1 HOLA MUNDO

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EmployeesCards
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield